### ISSUE TITLE
What are the odds of it hitting a code?

### ISSUE THREAD

**Issue by berrely** [Stanley-GF/Discord-Nitro-Generator#5]
Is it like a 1 in 10000 chance? More or less? Also, do you want me to help translate the project to English for other users?

**Comment by HuskyCodez** [comment]
> Is it like a 1 in 10000 chance? More or less? Also, do you want me to help translate the project to English for other users?

Likely chances are like once in a blue moon.

**Comment by Jeydin21** [comment]
0%, it's a scam

**Comment by Stanley-GF** [comment]
nah

**Comment by Jeydin21** [comment]
Ok, then tell me the chance then.

**Comment by AstroOrbis** [comment]
We don’t have specific odds. We just need 4 factors to line up:

1. Someone bought a Nitro
2. The generator is running
3. The generator randomly falls on the exact code that someone bought (i think it’s like 16 billion possibilities, gonna recheck that later)
4. You manage to claim the code before the person who actually bought it.

That’s how they all work

**Comment by ICExFS** [comment]
Man you can’t have nitro or you need to put your token on Check.cs because actually the owner just putted his own token so if you found a working code it’ll redeem on the owner’s account



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by Stanley-GF** [comment]
Nop I tried a autoclaimer invalid token
